DROP TABLE IF EXISTS auth_challenges CASCADE;
DROP TABLE IF EXISTS mailbox CASCADE;
DROP TABLE IF EXISTS rate_limit_buckets CASCADE;
DROP TABLE IF EXISTS token_blacklist CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS app_users CASCADE;
