package com.hermnet.api.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * Represents a user in the Hermnet system.
 * 
 * This entity stores the fundamental identity information for a user,
 * including their unique ID and public key used for secure communication.
 * It uses JPA annotations for database mapping and Lombok for boilerplate code
 * reduction.
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /**
     * The unique identifier for the user.
     * This ID is typically generated by the hasher or provided during creation.
     */
    @Id
    @Column(name = "id_hash", length = 64)
    private String idHash;

    /**
     * The public encryption key associated with the user.
     * This key is unique to each user and used for verifying identity or encrypting
     * messages.
     * Stored as TEXT to accommodate varying key lengths.
     */
    @Column(name = "public_key", nullable = false, columnDefinition = "TEXT", unique = true)
    private String publicKey;

    @Column(name = "push_token", columnDefinition = "TEXT")
    private String pushToken;

    /**
     * The timestamp when this user record was created.
     * Automatically populated before the entity is persisted to the database.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Lifecycle callback to set the creation timestamp.
     * Executed automatically by JPA before the entity is inserted into the
     * database.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }
}
